#server.port=8082
#security.oauth2.client.client-id=client2
#security.oauth2.client.client-secret=secret
#security.oauth2.client.access-token-uri=http://127.0.0.1:8080/oauth/token
#security.oauth2.client.user-authorization-uri=http://127.0.0.1:8080/oauth/authorize
#security.oauth2.resource.user-info-uri=http://127.0.0.1:8080/user/me
#

server:
  servlet:
    context-path: /client2
  port: 8082

auth-server: http://localhost:8080/authserver

security:
  oauth2:
    client:
      clientId: client2
      clientSecret: 123456
      accessTokenUri: ${auth-server}/oauth/token
      userAuthorizationUri: ${auth-server}/oauth/authorize
#      clientAuthenticationScheme: form
    resource:
      userInfoUri: ${auth-server}/user/me
      tokenInfoUri: ${auth-server}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG


#server:
#  servlet:
#    context-path: /client2
#  port: 8082
#
#security:
#  oauth2:
#    client:
#      clientId: client_1
#      clientSecret: 123456
#      accessTokenUri: http://127.0.0.1:8081/oauth/token
#      userAuthorizationUri: http://127.0.0.1:8081/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
##      userInfoUri: ${auth-server}/user/me
#      tokenInfoUri: http://127.0.0.1:8081/oauth/check_token
