#server.port=8082
#security.oauth2.client.client-id=client2
#security.oauth2.client.client-secret=secret
#security.oauth2.client.access-token-uri=http://127.0.0.1:8080/oauth/token
#security.oauth2.client.user-authorization-uri=http://127.0.0.1:8080/oauth/authorize
#security.oauth2.resource.user-info-uri=http://127.0.0.1:8080/user/me
#

security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
